# Generated by Django 4.0.4 on 2022-04-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_addr', models.CharField(max_length=50, unique=True)),
                ('isActive', models.BooleanField(default=False)),
                ('isConnected', models.BooleanField(default=False)),
                ('isBlocked', models.BooleanField(default=False)),
                ('isAction', models.CharField(default=False, max_length=50, null=True)),
                ('note', models.CharField(blank=True, choices=[('shutdown', 'SHUTDOWN'), ('restart', 'RESTART')], max_length=255, null=True)),
            ],
        ),
    ]
