# Generated by Django 4.0.4 on 2022-04-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userWifi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='computer',
            name='isAction',
            field=models.CharField(choices=[('noAction', 'NOACTION'), ('shutdown', 'SHUTDOWN'), ('restart', 'RESTART')], default=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='computer',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
