# Generated by Django 4.0.3 on 2022-05-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request_action',
            name='created',
            field=models.DateTimeField(auto_created=True, blank=True, null=True),
        ),
    ]
