# Generated by Django 4.0.3 on 2022-05-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API_web', '0002_request_action_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request_action',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
