# Generated by Django 4.0.3 on 2022-05-07 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API_web', '0004_computer_isalive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request_action',
            name='ip_addr',
        ),
    ]
